### ISSUE TITLE
Not running on java 1.8.0_101

### ISSUE THREAD

**Issue by ainthek** [PatMartin/Dex#10]
java.lang.RuntimeException: ControlsFX Error: ControlsFX 8.40.10 requires at least Java Version 8 Update 40

This is actually bug in controlsfx, https://bitbucket.org/controlsfx/controlsfx/issues/675/jdk-180_101-180_40#comment-29330543

please update version of dependent lib.

**Comment by ghost** [comment]
I met the same problem, and waiting for solusion.

**Comment by PatMartin** [comment]
Upgraded ControlsFX to the latest stable version and this fixed it on my end.

**Comment by d-pinto** [comment]
Pat - For those of us newbies - how exactly did you upgrade ControlsFX ?  I downloaded the 8.40.12 jar for controlsfx and placed it in the lib folder for Dex.  However when I doubleclick the .exe it doesn't seem to recognize that lib file.  Even after renaming the two existing controlsfx jar files to .OLDJar the app doesn't start with the one remaining controlsfx jar.  I have been able to get it to work by renaming the 8.40.12 file to 8.40.10 but I don't think that's the right way to do it ;)

Thanks for any clarification you or others on the thread can give!

**Comment by PatMartin** [comment]
I had to recompile the Dex.jar file via the ant build which updates the manifest which tells Dex to look for the newer version of controlsfx.

The exe is another matter.  I have to build that separately and tell it about the new files separately.  Its kind of a pain the butt, so I don't do it in the Github repo, but only when I update the actual prepackaged version.  What you did, renaming the jar is fine, and rather clever.

Given the breakage here, over my vacation, I'll put a new .exe out there, increment the minor version number and *ahem* try to do more testing first.

Another solution would have been to use an older version of Java.  Its kind of uncommon for later versions of Java to break things which worked in previous versions.  They've been carrying some of the deprecated stuff for over a decade now.

Sorry for being a slacker in responding...its been a very tough year for me and I don't get enough time to geek out anymore.

**Comment by PatMartin** [comment]
The distribution should run versus java 8 update 121 from git clone just fine now.
