### ISSUE TITLE
Where is the TMI groovy script?

### ISSUE THREAD

**Issue by robross0606** [PatMartin/Dex#11]
Looking for the referenced TMI groovy script in the source.  The .classpath file refers to an external Eclipse project.  Cannot seem to find the com.dexvis.tmi.* source.

**Comment by PatMartin** [comment]
Ah, that's a separate ANTLR project which I overlooked adding to Github.  Let me think through how
best to distribute it.  Either separately or as part of Dex proper.  Meanwhile, if you email me at patrick145@msn.com, I'll zip up the source for you as a stopgap measure.

- Pat

**Comment by PatMartin** [comment]
Sent and TMI is bundled as a Jar now.  Closing.
