### ISSUE TITLE
how to sort CSV Input by some columns ?

### ISSUE THREAD

**Issue by ainthek** [PatMartin/Dex#9]
I have browsed through docs and did not find it, any link please ?

**Comment by PatMartin** [comment]
There isn't a sorting task, but there's a ton of ways you could do it.

You could do it via one of the scripting components in the language of your choice.  Groovy, Ruby, Python, Javascript, etc...

Or by far, the easiest way would be to drop in the "Create Jdbc Database" component.  Take it's defaults.  It'll default to an in-memory, hyperSQL database.  It'll call the table CSV by default.

Then drop in a "Query Jdbc Database" component and do a

SELECT * FROM CSV ORDER BY <COLUMN_NAME> DESC;

or ascending, depending on what you want.

The in-memory db really comes in handy when it comes to some quick and dirty data manipulation.

- Pat
